[DontMerge][DevelOnly] Devel env for RBD IR support
Fhubik's development environment for the RHOSINFRA-4257
tracked in RHOSINFRA-4573, serves as:
* one big (cherrypicked) base for the feature
* to ease the headaches from dealing internal IR structure
around storage provisioning and XML post-processing
* hosting of supporting playbooks and commands for the devel
* devel tracker

RHOSINFRA-4573

Change-Id: I326b04c6f4e082fb6766f67b7bf15bba75282919

diff --git a/plugins/virsh/snapshot_export.yml b/plugins/virsh/snapshot_export.yml
--- a/plugins/virsh/snapshot_export.yml
+++ b/plugins/virsh/snapshot_export.yml
@@ -11,7 +11,7 @@
       package:
         name:
           - libguestfs-tools-c
-          - parallel
+          #- parallel TODO: not always available
         state: present
 
     - name: Get info about existing VM's
@@ -23,12 +23,21 @@
       set_fact:
         _vm_list: "{{ _virt_list.list_vms | select('match', vm_prefix ~ provision.virsh.snapshot.servers) | list }}"
 
+# TODO: detect cephfs, override path if detected? Maybe no, maybe use param rather?
+
+#    - name: If RBD is used, overwrite snapshot destination
+#      set_fact:
+#        provision.virsh.snapshot.path: "/mnt/mycephfs"
+
+    # TODO - figure this out - possibly replace with while loop or test disk1.os = True
     - name: Shut down any running VM's
       shell: |
         set -eo pipefail
         RETURN_CODE=0
         if ! virsh domstate {{ item }} | grep -qw 'shut off'; then
           virsh shutdown {{ item }}
+          sleep 5
+          virsh destroy {{ item }} || true
           RETURN_CODE=2
         fi
         exit ${RETURN_CODE}
@@ -39,6 +48,8 @@
       changed_when: _vm_stop.rc == 2
       failed_when: _vm_stop.rc not in [0, 2]
 
+# TODO ADD ACPI checks for VMs that do not have OS yet...
+
     - name: Wait for all VM's to be shut down
       command: |
         virsh domstate {{ item }}
@@ -46,8 +57,11 @@
       register: _vm_shutdown
       until: _vm_shutdown.stdout.find('shut off') != -1
       retries: "{{ vm_shutdown_timeout | default(30) }}"
-      delay: 60
+      delay: 10
       loop: "{{ _vm_list }}"
+
+#    - name: Fail
+#      fail: msg="Reached stop"
 
     - name: Make sure that the snapshot path exists
       file:
@@ -70,17 +84,26 @@
             dest: "{{ provision.virsh.snapshot.path }}/"
 
         - name: Sparsify and export disk images
-          shell: |-
-            set -o pipefail
-            DISK_LIST=""
-            for dom in {{ _vm_list | join(' ') }}; do
-              for vdisk in $(virsh domblklist $dom | awk "/$dom/ {print \$2}"); do
-                DISK_LIST="$DISK_LIST $vdisk"
-              done
+          shell: |
+            for vdisk in $(virsh domblklist {{ item }} | awk '/{{ item }}/ {print $2}'); do
+              virt-sparsify --in-place ${vdisk}
+              qemu-img convert -O qcow2 -c ${vdisk} {{ provision.virsh.snapshot.path }}/${vdisk##*/}
             done
-            parallel --will-cite --use-cores-instead-of-threads --jobs 50% 'virt-sparsify --in-place {}; qemu-img convert -O qcow2 -c {} {{ provision.virsh.snapshot.path }}/$(basename {})' ::: $DISK_LIST
           args:
             executable: /bin/bash
+          loop: "{{ _vm_list }}"
+          when: not provision.rbd.on
+
+        - name: Snapshot the states of all RBD images in image repository
+          ignore_errors: yes
+          shell: |
+            echo "{{ provision.rbd.namespace }}" > "{{ provision.virsh.snapshot.path }}/namespace-info.txt"
+            for vdisk in $(virsh domblklist {{ item }} | awk '/{{ item }}/ {print $2}'); do
+              rbd snap create ${vdisk}@{{ provision.rbd.snapname }}
+              rbd snap protect ${vdisk}@{{ provision.rbd.snapname }}
+            done
+          loop: "{{ _vm_list }}"
+          when: provision.rbd.on
 
         - name: Save nvram image
           shell: |
@@ -91,6 +114,7 @@
           args:
             executable: /bin/bash
           loop: "{{ _vm_list }}"
+          when: not provision.rbd.on
 
         - name: Save VM definitions
           copy:
diff --git a/plugins/virsh/tasks/vms_1_create_disk.yml b/plugins/virsh/tasks/vms_1_create_disk.yml
--- a/plugins/virsh/tasks/vms_1_create_disk.yml
+++ b/plugins/virsh/tasks/vms_1_create_disk.yml
@@ -2,13 +2,10 @@
 - set_fact:
     topology_node: "{{ node.value }}"
 
+#default: "/var/lib/libvirt/images"
 - name: define disk pool path
   set_fact:
-      disk_pool: "{{ provision.disk.pool if (topology_node.disks.disk1.path == None) else topology_node.disks.disk1.path }}"
-
-- name: define disk pool name
-  set_fact:
-      pool_name: "{{ provision.pool.name }}"
+      disk_pool: "{{ (provision.disk.pool if (topology_node.disks.disk1.path == None) else topology_node.disks.disk1.path) if not provision.rbd.on else rbd_namespace_url_libguestfs }}"
 
 - block:
       #todo(yfried): move this to verification section (before execution)
@@ -33,13 +30,16 @@
           follow: yes
         when: disk_pool | default(False)
 
-
       - name: Check volume pool
         command: >
           virsh pool-uuid "{{ pool_name }}"
         register: pool_check
         ignore_errors: true
         changed_when: false
+
+      - name: Print pool_check status
+        debug:
+            msg: "pool check is: {{pool_check}}"
 
       - name: create the volume pool xml file
         template:
@@ -49,24 +49,32 @@
 
       - name: Define volume pool
         command: "virsh pool-define /tmp/volume_pool.xml"
-        when: pool_check is failed
+        when:
+          - pool_check is failed
+          - provision.rbd.on
 
       - name: Start volume pool
         virt_pool:
           command: start
           state: active
           name: "{{ pool_name }}"
+        when: provision.rbd.on
 
       # Cannot be done in the same start operation as above, apparently
       - name: Mark volume pool as autostart
         virt_pool:
           name: "{{ pool_name }}"
           autostart: "yes"
+        when: provision.rbd.on
 
       # For disks usually it will be only 1 disk so the async will run on nodes rather than disks creation
       - name: create disk(s) from vm base image
         vars:
             net_scripts: /etc/sysconfig/network-scripts
+            libguestfs_opts: "{{ ' --format=raw ' if provision.rbd.on }}"
+            img_format: "{{ 'rbd' if provision.rbd.on else 'qcow2' }}"
+            base_image_path: "{{ rbd_namespace_url_libguestfs if provision.rbd.on }}"
+            #golden_image_name: "{{ provision.rbd.clonename }}@virsh"
         shell: |
             set -exo pipefail
             export LIBGUESTFS_PATH=/opt/appliance
@@ -74,33 +82,49 @@
 
             {% for num in topology_node.node_indexes %}
             {% for disk_name, disk_values in topology_node.disks.items() %}
-            {% set node_image = '{0}-{1}-{2}.qcow2'.format(topology_node.name, num, disk_name) %}
-            {% set image_name = (disk_values.import_url|default('') or topology_node.import_url|default('') or url) | basename %}
+            {% set node_image = '{0}-{1}-{2}.{3}'.format(topology_node.name, num, disk_name,img_format) %}
+            {% set image_name = (disk_values.import_url|default('') or topology_node.import_url|default('') or golden_image_name|default('')  or url) | basename %}
             {% if not disk_values.import_url %}
-
-            # create empty disk
-            qemu-img create -f qcow2 -o preallocation={{ disk_values.preallocation }} {{ disk_pool  }}/{{ node_image }} {{ disk_values.size }}
 
             ## Prepare disk image
 
             {% if disk_name == 'disk1' and topology_node.deploy_os|default(True) and topology_node.supports_libguestfs|default(True) -%}
-            # expand (copy-content) into new image in case of system disk
-            # virt-resize needs target file with expected size to already exists
-            os_version=`virt-cat -a {{ base_image_path }}/{{ image_name }} /etc/os-release | awk '/^VERSION=/ {print $1}' | grep -oP '[0-9]+' | head -1`
-            # Try to find the "root" partition or an first xfs partition. Defaults to /dev/sda1 else.
-            partitions=`virt-filesystems --csv --long --no-title -a {{ base_image_path }}/{{ image_name }}`
-            root_part=`awk -F "," '{ if ($4 == "root") {print $1; exit;} }' <<<"${partitions}"`
-            if [[ -z "$root_part" ]]; then
-                root_part=`awk -F "," '{ if ($3 == "xfs") {print $1; exit;} }' <<<"${partitions}"`
-            fi
+
+            device={{ rbd_namespace_url }}/{{ node_image }}
+
+            {% if provision.rbd.on %}
+            # if (rbd clone {{ rbd_clone_url }}@virsh {{ rbd_namespace_url }}/{{ node_image }}); then
+            rbd clone {{ golden_snapshot }} {{ rbd_namespace_url }}/{{ node_image }} || true
+            rbd resize --size {{ disk_values.size }} {{ rbd_namespace_url }}/{{ node_image }} || true
+            #if (rbd showmapped | grep "{{ node_image }}" |  awk -F " " '{print $4; exit;}' == {{ node_image }}); then
+            #  rbd_dev=`rbd showmapped | grep "{{ node_image }}" |  awk -F " " '{print $6; exit;}'`
+            #else
+              rbd_dev_old=`rbd map {{ rbd_namespace_url }}/{{ node_image }}`
+              rbd_dev=`rbd map {{ rbd_namespace_url }}/{{ node_image }}`
+            #fi
+            #fi
+            device=$rbd_dev
+            {% endif %}
+
+            echo "Image name is {{ image_name }}"
+            echo "device var is $device"
+            #exit 1
+
+            # Try to find the "root" partition or an xfs partition. Defaults to /dev/sda1 else.
+            root_part=`virt-filesystems {{ libguestfs_opts }} --csv --long --no-title -a $device | awk -F "," '{ if ($4 == "root") {print $1; exit;} else if ($3 == "xfs") {print $1; exit;} }'`
             root_part=${root_part:-/dev/sda1}
-            virt-resize --expand $root_part {{ base_image_path }}/{{ image_name }} {{ disk_pool }}/{{ node_image }}
+            # TODO replace base_imagE_path with rbd_clone_url@virsh everywhere here
+            # TODO2: virt-resize will fail raw disk and dest clone are the same size
+            # if disk_values.size not {{ rbd_namespace_url }}/{{ node_image }}; only then resize
+            #virt-resize {{ libguestfs_opts }} --expand $root_part {{ base_image_path }}/{{ image_name }} $device
             # We need to regenerate a new machine-id due to DHCP IPv6 not working otherwise
-            virt-sysprep --selinux-relabel -a {{ disk_pool }}/{{ node_image }} \
+            # TODO replace base_imagE_path with rbd_clone_url@virsh everywhere here
+            virt-resize {{ libguestfs_opts }} --expand $root_part $rbd_dev_old $device || true
+            virt-sysprep {{ libguestfs_opts }} -a $device \
                 --operations machine-id
             # inject DEFROUTE for IPv6 and IPv6 to file and set it on for external network only
             NIC_DEFAULT="DEVICE=\"eth0\"\nBOOTPROTO=\"dhcp\"\nBOOTPROTOv6=\"dhcp\"\nONBOOT=\"yes\"\nTYPE=\"Ethernet\"\nUSERCTL=\"yes\"\nPEERDNS=\"yes\"\nIPV6INIT=\"yes\"\nPERSISTENT_DHCLIENT=\"1\"\n"
-            virt-customize -a {{ disk_pool }}/{{ node_image }} \
+            virt-customize {{ libguestfs_opts }} -a $device --selinux-relabel \
             {% for interface in topology_node.interfaces %}
                 {% if loop.index0 == 0 %}
                     --run-command "echo -e \"$NIC_DEFAULT\" > {{ net_scripts }}/ifcfg-eth{{ loop.index0 }}" \
@@ -117,14 +141,26 @@
                 --run-command 'echo /swapfile none swap defaults 0 0 >> /etc/fstab' \
             {% endif -%}{# endif swap #}
                 --selinux-relabel
-            {% endif %}{# endif disk1 #}
+            {# TODO maybe better approach would be using the import workflow and doing RBD there #}
+            {# we do not work with deploy_os enabled diskX - e.g. controller, compute disks or first ceph disk #}
+            {# (meaning we work with silver rbd image here) #}
+            {% elif disk_name == 'disk1' and not topology_node.deploy_os|default(True) %}
+                rbd clone {{ silver_snapshot }} {{ rbd_namespace_url }}/{{ node_image }} || true
+                rbd resize --size {{ disk_values.size }} {{ rbd_namespace_url }}/{{ node_image }} || true
+            # Otoh some VMs need dummy image to customize it based on deployed app(ceph), that is created here
+            {% else %}
+                {# we work with empty disk - like ceph node disks2-x ready for tripleO ceph deployment #}
+                rbd create --size {{ disk_values.size }} {{ rbd_namespace_url }}/{{ node_image }} || true
+            {% endif %}{# endif disk1, topology_node, libguests #}
 
             # todo(yfried): use builtin module for chown
             {% else %}{# else import_url #}
             # in case of import simply copy that image to use as a disk
             cp -rf {{ base_image_path }}/{{ image_name }} {{ disk_pool }}/{{ node_image }}
             {% endif %}{# endif not import_url #}
+            {% if not provision.rbd.on %}
             chown qemu:qemu {{ disk_pool }}/{{ node_image }}
+            {% endif %}
             {% endfor %}{# endfor vm disks #}
             {% endfor %}{# endfor vm-type(controller etc) #}
       #  todo(yfried) needs a "creates"
@@ -132,6 +168,7 @@
       #      creates: "create disk(s) from vm base image"
         register: vm_disks
         async: 7200
+        delay: 5
         poll: 0
 
       - name: save disks jids
