[DontMerge][DevelOnly] Debug env for RBD storage XML postprocessing
Fhubik's development environment for the RHOSINFRA-4257
to ease the headaches from dealing internal IR structure
around storage provisioning and XML post-processing.

Change-Id: I326b04c6f4e082fb6766f67b7bf15bba75282919

diff --git a/plugins/virsh/tasks/vms_1_create_disk.yml b/plugins/virsh/tasks/vms_1_create_disk.yml
--- a/plugins/virsh/tasks/vms_1_create_disk.yml
+++ b/plugins/virsh/tasks/vms_1_create_disk.yml
@@ -6,10 +6,6 @@
   set_fact:
       disk_pool: "{{ provision.disk.pool if (topology_node.disks.disk1.path == None) else topology_node.disks.disk1.path }}"
 
-- name: define disk pool name
-  set_fact:
-      pool_name: "{{ provision.pool.name }}"
-
 - block:
       #todo(yfried): move this to verification section (before execution)
       - name: verify swap is within disk1 size
@@ -67,6 +63,10 @@
       - name: create disk(s) from vm base image
         vars:
             net_scripts: /etc/sysconfig/network-scripts
+            libguestfs_opts: "{{ ' --format=raw ' if provision.rbd.on }}"
+            img_format: "{{ 'rbd' if provision.rbd.on else 'qcow2' }}"
+            base_image_path: "{{ rbd_namespace_url_libguestfs if provision.rbd.on }}"
+            #golden_image_name: "{{ provision.rbd.clonename }}@virsh"
         shell: |
             set -exo pipefail
             export LIBGUESTFS_PATH=/opt/appliance
@@ -84,19 +84,39 @@
             ## Prepare disk image
 
             {% if disk_name == 'disk1' and topology_node.deploy_os|default(True) and topology_node.supports_libguestfs|default(True) -%}
-            # expand (copy-content) into new image in case of system disk
-            # virt-resize needs target file with expected size to already exists
-            os_version=`virt-cat -a {{ base_image_path }}/{{ image_name }} /etc/os-release | awk '/^VERSION=/ {print $1}' | grep -oP '[0-9]+' | head -1`
+
+            device={{ rbd_namespace_url }}/{{ node_image }}
+
+            {% if provision.rbd.on %}
+            # if (rbd clone {{ rbd_clone_url }}@virsh {{ rbd_namespace_url }}/{{ node_image }}); then
+            rbd clone {{ rbd_clone_url }}@virsh {{ rbd_namespace_url }}/{{ node_image }} || true
+            rbd resize --size {{ disk_values.size }} {{ rbd_namespace_url }}/{{ node_image }} || true
+            if (rbd showmapped | grep "{{ node_image }}" |  awk -F " " '{print $4; exit;}' == {{ node_image }}); then
+              rbd_dev=`rbd showmapped | grep "{{ node_image }}" |  awk -F " " '{print $6; exit;}'`
+            else
+              rbd_dev=`rbd map {{ rbd_namespace_url }}/{{ node_image }}`
+            fi
+            #fi
+            device=$rbd_dev
+            {% endif %}
+
+            echo "Image name is {{ image_name }}"
+            echo "device var is $device"
+            #exit 1
+
             # Try to find the "root" partition or an xfs partition. Defaults to /dev/sda1 else.
-            root_part=`virt-filesystems --csv --long --no-title -a {{ base_image_path }}/{{ image_name }} | awk -F "," '{ if ($4 == "root") {print $1; exit;} else if ($3 == "xfs") {print $1; exit;} }'`
+            root_part=`virt-filesystems {{ libguestfs_opts }} --csv --long --no-title -a $device | awk -F "," '{ if ($4 == "root") {print $1; exit;} else if ($3 == "xfs") {print $1; exit;} }'`
             root_part=${root_part:-/dev/sda1}
-            virt-resize --expand $root_part {{ base_image_path }}/{{ image_name }} {{ disk_pool }}/{{ node_image }}
+            # TODO replace base_imagE_path with rbd_clone_url@virsh everywhere here
+            # TODO2: virt-resize will fail raw disk and dest clone are the same size
+            # if disk_values.size not {{ rbd_namespace_url }}/{{ node_image }}; only then resize
+            #virt-resize {{ libguestfs_opts }} --expand $root_part {{ base_image_path }}/{{ image_name }} $device
             # We need to regenerate a new machine-id due to DHCP IPv6 not working otherwise
-            virt-sysprep -a {{ disk_pool }}/{{ node_image }} \
+            virt-sysprep {{ libguestfs_opts }} -a $device \
                 --operations machine-id
             # inject DEFROUTE for IPv6 and IPv6 to file and set it on for external network only
             NIC_DEFAULT="DEVICE=\"eth0\"\nBOOTPROTO=\"dhcp\"\nBOOTPROTOv6=\"dhcp\"\nONBOOT=\"yes\"\nTYPE=\"Ethernet\"\nUSERCTL=\"yes\"\nPEERDNS=\"yes\"\nIPV6INIT=\"yes\"\nPERSISTENT_DHCLIENT=\"1\"\n"
-            virt-customize -a {{ disk_pool }}/{{ node_image }} \
+            virt-customize {{ libguestfs_opts }} -a $device --selinux-relabel \
             {% for interface in topology_node.interfaces %}
                 {% if loop.index0 == 0 %}
                     --run-command "echo -e \"$NIC_DEFAULT\" > {{ net_scripts }}/ifcfg-eth{{ loop.index0 }}" \
@@ -113,6 +133,9 @@
                 --run-command 'echo /swapfile none swap defaults 0 0 >> /etc/fstab' \
             {% endif -%}{# endif swap #}
                 --selinux-relabel
+            {% else %}{# we do not work with deploy_os enabled diskX - e.g. ceph disks #}
+                # todo: with RBD, we dont want to create anything, just clone from golden images = even dummy VMs
+                rbd create --size {{ disk_values.size }} {{ rbd_namespace_url }}/{{ node_image }}
             {% endif %}{# endif disk1 #}
 
             # todo(yfried): use builtin module for chown
